### ISSUE TITLE
Litters body tag with pg-loaded classes

### ISSUE THREAD

**Issue by nozpheratu** [Pathgather/please-wait#10]
It seems that repeated starting and `finish()` calls to this plugin litters the body tag with excess `pg-loaded` classes. Reproducable on the [demo page](http://pathgather.github.io/please-wait/?utm_source=javascriptweekly&utm_medium=email) simply repeatedly close and re-open the demo and watch the body tag get bombarded with `pg-loaded` classes.

**Comment by nozpheratu** [comment]
Perhaps an easy work around be be providing a way to re-display the loading screen for an existing please wait object. That way we wouldn't need to initialize a new screen every time it needed to be displayed.

**Comment by NevilleS** [comment]
I'm glad you noticed that - thanks! I'll take a look.
