### ISSUE TITLE
Loading screen flashes when finishing

### ISSUE THREAD

**Issue by zlangbert** [Pathgather/please-wait#13]
I'm seeing this in your demo and in my own app: when closing the loading screen it will flash white before fading out. I'm on Windows 10 and have tried the latest Chrome and Firefox.

**Comment by NevilleS** [comment]
I think I know what you mean, I submitted a PR for our demo page recently and haven't gotten around to double-checking the fix and merging it there.

The flash is likely caused by how you've set up the CSS to hide the body while `.pg-loaded` is active. See #12 for a likely fix for your app.

**Comment by zlangbert** [comment]
That did the trick, thanks!

**Comment by NevilleS** [comment]
No problem :)
