### ISSUE TITLE
Not able to close in any browser

### ISSUE THREAD

**Issue by PKudupu** [Pathgather/please-wait#15]
<code> 
scope.Show = function() {
             window.loading_screen = window.pleaseWait({
logo:"http://api.ning.com/files/3dClu3zYZusfVojQVtAQJSlleasTbCK0wguJlqXDoAnV019BCyihQU6l1TpjhrxSOpuBsnILlOSgzZwoaFkSpPGluDm39lCs/bnationheader.png",
                backgroundColor: '#3366ff',
                loadingHtml: "<div class='sk-spinner sk-spinner-pulse'><div class='sk-rect1'></div><div class='sk-rect2'></div><div class='sk-rect3'></div><div class='sk-rect4'></div><div class='sk-rect5'></div></div>"
      });
            window.setTimeout(function () {
                loading_screen.finish();
            }, 3000);
        }
</code>

**Comment by qrtise** [comment]
Are you using script tags 
scope.Show = function() { window.loading_screen = window.pleaseWait({ logo:"http://api.ning.com/files/3dClu3zYZusfVojQVtAQJSlleasTbCK0wguJlqXDoAnV019BCyihQU6l1TpjhrxSOpuBsnILlOSgzZwoaFkSpPGluDm39lCs/bnationheader.png", backgroundColor: '#3366ff', loadingHtml: "

<script>
 window.onload=function(){
 window.setTimeout(function(){
 loading_screen.finish();
        },3000
   );
  }
</script>
