### ISSUE TITLE
Controlling minimal display time

### ISSUE THREAD

**Issue by Martinsos** [Pathgather/please-wait#16]
Thank you for this great library!
There seems to be a minimal display time before please-wait splash screen closes.
In case when my page loads really fast, I have to wait for splash screen for that time and only then will it dissapear. Is there any way to control that, to make it dissapear as soon as `finish()` is called, even if it that was very quickly after the creation of splash screen?
Thanks

**Comment by NevilleS** [comment]
Yeah, the animation durations are controlled via CSS, and the loading screen registers listeners to wait for the animation events to fire before proceeding through it's finishing sequence.

The `finish` method does take arguments, though (https://github.com/Pathgather/please-wait/blob/master/src/please-wait.coffee#L167). The first argument is a boolean `immediately`, which when set to true, will cause the screen to disappear without any animations at all, which might be what you want.

e.g.

```
var loading_screen = pleaseWait({ ... }});

// some time later
loading_screen.finish(true); // finishes immediately, no animations
```

**Comment by Martinsos** [comment]
Thanks @NevilleS, that is it! Is there a reason why this functionality is not documented?
