### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by diegoalmesp** [Pathgather/please-wait#17]
Hi! great plugin!

I'm having this problem when loading in my app (w/angular), is very weird

Uncaught TypeError: Cannot read property 'classList' of null this message appear at the line 76 of the js file inside the removeClass function.

I also tried to create an index file, load everything (to discard problems with my app) but it's still happening

Any ideas?

Thanks in advance!

**Comment by diegoalmesp** [comment]
NEVERMIND!! 

Sorry, I just moved the portion of code to create the page at the bottom under the body and now works.

Thanks!!

**Comment by andreadompe** [comment]
I've got the same problem!
Please help me.
