### ISSUE TITLE
Loading Page Loaded After Some Elements

### ISSUE THREAD

**Issue by Behseini** [Pathgather/please-wait#18]
Hi,
Thanks for this great library but I am having some issue on loading the loader on Bootstrap. In my case the loader shows up few seconds after page and some elements appears on the screen!

[Here is a Link](http://goproweb.ca/xxar/index.php) of what happening.

Can you please let me know why this is happening? (As you can see the loader appears not first element on the page!) 

Thanks

**Comment by NevilleS** [comment]
See the section "Hide initial HTML flash" on the docs: http://pathgather.github.io/please-wait/

Also note that you should include and launch the PleaseWait JS file as soon as possible, before all your other JS files, if you aren't doing that already. This will reduce the time your unloaded page is shown.

**Comment by Behseini** [comment]
Great!
Thanks it is working perfectly now
