### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by Pigrecolab** [Pathgather/please-wait#22]
I've a lot of troubles adding please wait in a page with masonry. I could add the masonry after finish(), but I don't know how to add a callback function... Could you help me ?

**Comment by jhdavids8** [comment]
I only know a little about masonry, but it sounds like you should probably follow this workflow:
- Show PleaseWait
- Do what you need with masonry and the layout
- Once masonry has finished, close PleaseWait

If you have a specific error you're running into though, please elaborate and we'll try to help!

**Comment by Pigrecolab** [comment]
Hello, the issue is due to:
`body { display: none }` 
befor pleaseWait finishes. I replaced it with:
`body { opacity: 0 }`..
Another important issue is about Android browser which doesn't close the splash screen at finish()
