### ISSUE TITLE
Adjust speed of animation

### ISSUE THREAD

**Issue by lukee910** [Pathgather/please-wait#23]
Is there a way to adjust the speed of the animation? I ask in order to use it as a loading panel while loading some data. That data takes between 200 and 500ms to load and will be loaded before the animation finishes, which means the animation slows the page down.

I tried using `.finish(true)`, but that has the consequence of only showing a short flicker if the loading time is too short.

**Comment by NevilleS** [comment]
The animations are all defined in the CSS, so it should be relatively easy to write some rules in your stylesheet to override them. For example, [this rule](https://github.com/Pathgather/please-wait/blob/master/build/please-wait.css#L36) defines the speed that the inner element fade in, etc.

**Comment by NevilleS** [comment]
Let me know if you have any issues with that, but tweaking the CSS should give you what you need!
