### ISSUE TITLE
updateLoadingHtml isn't working

### ISSUE THREAD

**Issue by Meldinoor** [Pathgather/please-wait#24]
When I call updateLoadingHtml, with or without the "immediate" flag set to true, my loading html disappears and is not replaced with a new one. I've discovered that it is due to the pg-removing class not being removed and the html thus having opacity: 0.
I debugged the code and found that the listener that captures the animation event, calls the method _changeLoadingHtml() which removes the pg-removing class, but then immediately puts it back again. This seems a little odd. Am I missing something, or is this a bug?

**Comment by matte00** [comment]
Is this project stopped? I confirm. UpdateLoadingHtml doesn't works

**Comment by ianhattendorf** [comment]
I've forked the project and disabled transition support, which is the reason the `pg-removing` class wasn't being removed (for some reason the transition event isn't being fired). Updating the loading HTML is now working for me, with the caveat that there aren't any nice transitions.

https://github.com/ianhattendorf/please-wait

**Comment by Toilal** [comment]
I workaround this issue by performing direct DOM manipulation of HTML I want to change from initial one.

```typescript
  setLoadingMessage(message: string) {
    let element = document.querySelector('.pg-loading-html .loading-message');
    if (element) {
      element.innerHTML = message;
    }
  }

  setLoadingError(error: boolean) {
    let loadingElement = document.body;
    if (loadingElement) {
      if (error) {
        loadingElement.classList.add('pg-loading-error');
      } else {
        loadingElement.classList.remove('pg-loading-error');
      }
    }
  }
```
