### ISSUE TITLE
How to transparent background

### ISSUE THREAD

**Issue by TechGuyVN** [Pathgather/please-wait#26]
Hi,

I want use please-wait to block ui when request network, how can i do it?
Please help!

**Comment by lukee910** [comment]
Hello

I use the please-wait in the same way as you try to. You'll have to adjust the color in the panel config:

```
var _loadingPanel;
var _panelConfig = {
    backgroundColor: 'rgba(0, 0, 0, 0.5)', // You can adjust the color to your liking here
    logo: 'resources/logo_white.png', // White works best with this dark color
    loadingHtml: '<i class="fa fa-spinner fa-spin fa-4x fa-fw text-white"></i>' // The text to be displayed, in this case just a simple fontawesome spinner
};
```

[Fontawesome](http://fontawesome.io/examples/)

Then, you can do this when you start the request:

```
_loadingPanel = window.pleaseWait(_panelConfig);
```

And after receiving the response:

```
_loadingPanel.finish();
```

One problem I came across was that the animation is very slow. You can adjust that via CSS:

```
.pg-loading-screen.pg-loading .pg-loading-logo-header,
.pg-loading-screen.pg-loading .pg-loading-html:not(.pg-loaded) {
  -webkit-animation: pgAnimLoading 0.5s cubic-bezier(0.7, 0, 0.3, 1) both;
          animation: pgAnimLoading 0.5s cubic-bezier(0.7, 0, 0.3, 1) both;
}
```

**Comment by NevilleS** [comment]
Thanks @lukee910! Yes, you can definitely style the screen in a variety of ways, both via the Javascript API we've provided and overriding the CSS. If there's a bug preventing that from working, though, let us know...
