### ISSUE TITLE
Add option to enable full background mp4 video

### ISSUE THREAD

**Issue by montogeek** [Pathgather/please-wait#3]
This is a design trend for 2015. Full background videos on the intro page. Nice to have!

**Comment by jhdavids8** [comment]
PleaseWait isn't meant to be open for too long, so using bandwidth to load and play a video which could instead be used to load your app may not be the best route to take. That said, there are libraries like [BigVideo.js](http://dfcb.github.io/BigVideo.js/) which are geared towards doing just what you're looking for, so I'd recommend that instead.
