### ISSUE TITLE
ES6 import/require

### ISSUE THREAD

**Issue by dzackgarza** [Pathgather/please-wait#31]
Just wondering if this module is compatible with ES6-style imports. I've tried the following, with these corresponding results:

```
import pleaseWait from 'please-wait';
const loadingScreen = pleaseWait({ ... })
-> (0 , _pleaseWait2.default) is not a function
```

```
const pleaseWait = require('please-wait');
const loadingScreen = pleaseWait({ ... })
-> pleaseWait is not a function
```

**Comment by guncha** [comment]
It's certainly compatible with ES6 style imports.

```js
import {pleaseWait} from "please-wait"
```

**Comment by dzackgarza** [comment]
I did manage to figure that out after digging into the source, but would it be possible to make that function the default export?  

And would it be possible to add this to the documentation somewhere? Along with the path for the extra css files that need to be imported when you install via NPM?

**Comment by guncha** [comment]
We can certainly document it. As for the default import, my personal opinion is that it doesn't add a whole lot of usability while still adding complexity. Since we can't deprecate the old, but still ES6 compatible way to import the function, why have two? Default exports as well as replacing the whole `exports` object with something else like the `pleaseWait` function should have never been a thing, but, alas, I don't make the rules.

**Comment by dustinaevans** [comment]
I'm having an issue with this as well... I'm new to webpack so it may be a problem with my configuration. But I have imported pleaseWait as described above ``import {pleaseWait} from 'please-wait';``  and still get ``Uncaught ReferenceError: pleaseWait is not defined``

**Comment by dzackgarza** [comment]
Here's the way I wound up getting it to work:

```javascript
import pw from 'please-wait';

pw.pleaseWait({
 logo: 'someurl'
 // etc
});
```

**Comment by guncha** [comment]
@dzackgarza I really don't understand how it could work like that. Are you using Babel? The PleaseWait module just adds a `pleaseWait` property on the `exports` object - I can't see how that would end up as the default.

**Comment by dustinaevans** [comment]
I ended up using the CSS but not the javascript. PITA.

**Comment by dzackgarza** [comment]
@guncha Yep, that was in a webpack setup with babel-loader and babel-polyfill. I don't profess to know how or why it works, but it did seem to do the trick!

Some relevant parts of the config:

```javascript
const config = {
   ...
   entry: {
     dashboard: ['babel-polyfill', './frontend/dashboard.js']
   },
   ...
  module: {
    loaders: [
      ...
        {
          test: /\.js$/,
          use: 'babel-loader'
        },
      ]
    }
};
```

Some of the babel -related packages used:
```javascript
"babel-cli": "^6.26.0",
"babel-loader": "^7.1.2",
"babel-minify-webpack-plugin": "^0.2.0",
"babel-plugin-syntax-object-rest-spread": "^6.13.0",
"babel-plugin-transform-object-rest-spread": "^6.26.0",
"babel-polyfill": "^6.26.0",
"babel-preset-env": "^1.6.0",
"babel-core": "^6.26.0",
"babel-eslint": "^7.2.3",
```
