### ISSUE TITLE
This plugin is not good

### ISSUE THREAD

**Issue by ItsDanielHarris** [Pathgather/please-wait#33]
Does not close the loading screen.

I put the loading_screen.finish() command in nested $(document).ready and window.onload and it doesn't work. Lost hundreds of potential clients because of this.

**Comment by NevilleS** [comment]
Hey @TheWebAuthor... sorry for your trouble. As you can see on http://pathgather.github.io/please-wait/ demo, the `finish()` command does hide the screen for us, and we haven't modified the code in some time. If you are able to track down the specific problem in your setup, let us know.

**Comment by dunklesToast** [comment]
I think you need to use `window.loading_screen.finish()`!
