### ISSUE TITLE
css for spinners not included in Bower package

### ISSUE THREAD

**Issue by jeffcressman** [Pathgather/please-wait#6]
I just installed please-wait via Bower but the CSS for the spinners, in `default.css` on your demo site, is not included in the Bower package.

Maybe move the spinner and any other necessary CSS into another CSS file?

Cheers

**Comment by jhdavids8** [comment]
Hey Jeff,

The spinners are just examples from the excellent [Spinkit library](http://tobiasahlin.com/spinkit/), which has its own repo. They are purely for demonstration and not a requirement, as you can use any HTML/CSS you like with PleaseWait.

Hope that helps!
